### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Ureisen** [RizwanMunawar/yolov7-segmentation#20]
Hi!
I encountered such an error in the training process of using my own dataset (exported by RoboFlow). Is it because I have only one segmentation object?
It will be appreciated if you could give me some suggestions！

Traceback (most recent call last):
  File "train.py", line 613, in <module>
    main(opt)
  File "train.py", line 509, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 291, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/home/yolov7-segmentation-main/utils/loss.py", line 127, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/home/yolov7-segmentation-main/utils/loss.py", line 200, in build_targets
    anchors, shape = self.anchors[i], p[i].shape
AttributeError: 'list' object has no attribute 'shape'

**Comment by AndrewTKent** [comment]
@Ureisen I have the same issue, did you figure out the solution?

**Comment by RizwanMunawar** [comment]
@AndrewTKent! What is the format of your labels, its in coco format or YOLO format?

**Comment by AndrewTKent** [comment]
@RizwanMunawar Hi! Yes I have it in coco format (JSON) and I'm working out of a folder called coco_custom, and I have a coco_custom.yaml pointing to this folder

coco_custom
            │--annotations
            |          |--instances_default.json
            │--images
            |        |--train
            |         |       |--*.jpg
            |        |--val
            |         |       |--*.jpg
            │--train.txt
            │--val.txt

**Comment by goeunnykim** [comment]
> @AndrewTKent! What is the format of your labels, its in coco format or YOLO format?

Hi! Is it fixed? I have the same issue. My dataset is in yolo format.

**Comment by RizwanMunawar** [comment]
> @RizwanMunawar Hi! Yes I have it in coco format (JSON) and I'm working out of a folder called coco_custom, and I have a coco_custom.yaml pointing to this folder
> 
> coco_custom │--annotations | |--instances_default.json │--images | |--train | | |--_.jpg | |--val | | |--_.jpg │--train.txt │--val.txt

@AndrewTKent The format is wrong, you will need to convert the labels to yolo (Polygon box) format. Also I will recommend to follow the tutorial for data labeling, that I already recommended for proper training.
https://medium.com/augmented-startups/train-yolov7-segmentation-on-custom-data-b91237bd2a29

**Comment by RizwanMunawar** [comment]
> > @AndrewTKent! What is the format of your labels, its in coco format or YOLO format?
> 
> Hi! Is it fixed? I have the same issue. My dataset is in yolo format.

The required labeling format is Polygon box (with YOLO format). you will need to convert the labels to yolo (Polygon box) format. Also I will recommend to follow the tutorial for data labeling, that I already recommended for proper training.
https://medium.com/augmented-startups/train-yolov7-segmentation-on-custom-data-b91237bd2a29

**Comment by stephansturges** [comment]
I have this with the existing code base as well, with labels in YOLO format... digging into it to propose a fix.

**Comment by LeonardJiao** [comment]
> I have this with the existing code base as well, with labels in YOLO format... digging into it to propose a fix.

Hi! Have you fixed this issue? My data is  in yolo format but still error

**Comment by 5JM** [comment]
It's late, but I'll leave it here in case anyone gets lost.
If an error occurs even in YOLO format

Check you are running `./segment/train.py`.
(Not `./train.py`)
