### ISSUE TITLE
不同级别目录的.py文件不能相互调用

### ISSUE THREAD

**Issue by 2662448726** [RizwanMunawar/yolov7-segmentation#43]
不同级别目录的.py文件不能相互调用
Traceback (most recent call last):
  File "segment/predict.py", line 24, in <module>
    from models.common import DetectMultiBackend
  File "/mnt/yolov7-segmentation/models/common.py", line 28, in <module>
    from utils.general import (LOGGER, ROOT, Profile, check_requirements, check_suffix, check_version, colorstr,
ModuleNotFoundError: No module named 'utils.general'

**Comment by RizwanMunawar** [comment]
@2662448726! Uninstall the utils package with the mentioned command below and then try again. Seems like the utils package is pre-installed and the code is using the function from that package instead of a specifically defined and implemented function.

```
pip uninstall imutils
python3 segment/predict.py --weights yolov7-seg.pt --source "videopath.mp4"
```
