### ISSUE TITLE
segment/predict.py google colab error

### ISSUE THREAD

**Issue by aaaansnsn** [RizwanMunawar/yolov7-segmentation#7]
Code: 

!python segment/predict.py --weights "/content/yolov7-segmentation/runs/train-seg/yolov7-seg2/weights/best.pt" --source "/content/yolov7-segmentation/person-2/test/images/*"

Error:

Traceback (most recent call last):
  File "segment/predict.py", line 12, in <module>
    from sort_count import *
  File "/content/yolov7-segmentation/segment/sort_count.py", line 40, in <module>
    matplotlib.use('TkAgg')
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/deprecation.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py", line 1281, in use
    plt.switch_backend(name)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py", line 237, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

how to fix??

**Comment by RizwanMunawar** [comment]
@aaaansnsn! it seems that the matplotlib version is causing an issue. Please try to upgrade pip first and then install matplotlib. Hope it will works.
`pip install --upgrade pip & pip install matplotlib`

Then run the command again.
```!python segment/predict.py --weights "/content/yolov7-segmentation/runs/train-seg/yolov7-seg2/weights/best.pt" --source "/content/yolov7-segmentation/person-2/test/images/"```

For more details, you can get help from [link](https://stackoverflow.com/a/71511579)

**Comment by aaaansnsn** [comment]
thanks!

editing requirements.txt file 

matplotlib>=3.2.2 -->> matplotlib==2.2.4

solved this issue!

**Comment by RizwanMunawar** [comment]
I am closing this issue as completed, If you will face any issue, feel free to open new issue again. Thanks
