### ISSUE TITLE
PKL problem

### ISSUE THREAD

**Issue by gavintobin** [RizwanMunawar/yolov7-segmentation#72]
Transferred 566/566 items from yolov7_training.pt
Scaled weight_decay = 0.0005
Optimizer groups: 95 .bias, 95 conv.weight, 98 other
Traceback (most recent call last):
  File "/content/yolov7/train.py", line 616, in <module>
    train(hyp, opt, device, tb_writer)
  File "/content/yolov7/train.py", line 245, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/content/yolov7/utils/datasets.py", line 69, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/content/yolov7/utils/datasets.py", line 392, in __init__
    cache, exists = torch.load(cache_path), True  # load
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1434, in _load
    data_file = io.BytesIO(zip_file.get_record(pickle_file))
RuntimeError: PytorchStreamReader failed locating file data.pkl: file not found
[]

**Comment by gavintobin** [comment]
not really sure why im getting this error. Everything ran fine before i tried loggin to wandb now im getting this
